#!/usr/bin/env python

import sys
import sync_master

if len(sys.argv) >= 2:
    if sys.argv[1] != '--root':
        print('Available option : --root')
        exit()
    else:        
        sync_master.main_tcp(sys.argv[1])
else:
    sync_master.main_tcp('none')